# Generated by Django 5.1.7 on 2025-03-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="due_date",
        ),
    ]
