# Generated by Django 5.1.7 on 2025-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_todo_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
