# Generated by Django 5.1.7 on 2025-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_created_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "Todo", "verbose_name_plural": "Todos"},
        ),
        migrations.AddField(
            model_name="todo",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
