# Generated by Django 5.1.7 on 2025-03-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_todo_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["position", "status", "priority"],
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
        migrations.AddField(
            model_name="todo",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
