# Generated by Django 5.1.7 on 2025-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_alter_todo_options_todo_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": [
                    models.Case(
                        models.When(status="in_progress", then=1),
                        models.When(status="pending", then=2),
                        models.When(status="completed", then=3),
                        default=4,
                        output_field=models.IntegerField(),
                    ),
                    models.Case(
                        models.When(priority="high", then=1),
                        models.When(priority="medium", then=2),
                        models.When(priority="low", then=3),
                        default=4,
                        output_field=models.IntegerField(),
                    ),
                    "position",
                ],
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="category",
            new_name="tag",
        ),
    ]
